import type { Department } from "@/lib/types";

export const departments: Department[] = [
  // NovaTech Solutions
  {
    id: "novatech-engineering",
    tenantId: "novatech",
    name: "Engineering",
    description: "Product engineering, infrastructure and platform reliability.",
    color: "var(--chart-1)",
    budget: 18_500_000,
    headId: "novatech-emp-002",
  },
  {
    id: "novatech-product",
    tenantId: "novatech",
    name: "Product",
    description: "Product strategy, discovery and roadmap planning.",
    color: "var(--chart-2)",
    budget: 4_200_000,
    headId: "novatech-emp-006",
  },
  {
    id: "novatech-design",
    tenantId: "novatech",
    name: "Design",
    description: "Product design, brand and user research.",
    color: "var(--chart-3)",
    budget: 3_100_000,
    headId: "novatech-emp-007",
  },
  {
    id: "novatech-sales",
    tenantId: "novatech",
    name: "Sales",
    description: "New business, account management and partnerships.",
    color: "var(--chart-4)",
    budget: 6_800_000,
    headId: "novatech-emp-008",
  },
  {
    id: "novatech-marketing",
    tenantId: "novatech",
    name: "Marketing",
    description: "Brand, demand generation and lifecycle marketing.",
    color: "var(--chart-5)",
    budget: 2_900_000,
    headId: "novatech-emp-010",
  },
  {
    id: "novatech-finance",
    tenantId: "novatech",
    name: "Finance",
    description: "Financial planning, accounting and payroll operations.",
    color: "var(--chart-1)",
    budget: 2_400_000,
    headId: "novatech-emp-011",
  },
  {
    id: "novatech-people",
    tenantId: "novatech",
    name: "People & Culture",
    description: "Talent acquisition, HR operations and employee experience.",
    color: "var(--chart-2)",
    budget: 1_900_000,
    headId: "novatech-emp-001",
  },
  {
    id: "novatech-success",
    tenantId: "novatech",
    name: "Customer Success",
    description: "Onboarding, support and account retention.",
    color: "var(--chart-3)",
    budget: 3_400_000,
    headId: "novatech-emp-013",
  },

  // Apex Financial Group
  {
    id: "apex-advisory",
    tenantId: "apex",
    name: "Investment Advisory",
    description: "Portfolio management and client investment strategy.",
    color: "var(--chart-1)",
    budget: 22_000_000,
    headId: "apex-emp-002",
  },
  {
    id: "apex-risk",
    tenantId: "apex",
    name: "Risk & Compliance",
    description: "Regulatory compliance, audit and risk management.",
    color: "var(--chart-2)",
    budget: 7_600_000,
    headId: "apex-emp-005",
  },
  {
    id: "apex-finance",
    tenantId: "apex",
    name: "Finance & Accounting",
    description: "Group finance, accounting and treasury.",
    color: "var(--chart-3)",
    budget: 5_300_000,
    headId: "apex-emp-007",
  },
  {
    id: "apex-operations",
    tenantId: "apex",
    name: "Operations",
    description: "Client operations, settlements and back office.",
    color: "var(--chart-4)",
    budget: 6_100_000,
    headId: "apex-emp-009",
  },
  {
    id: "apex-technology",
    tenantId: "apex",
    name: "Technology",
    description: "Core banking systems, data and security.",
    color: "var(--chart-5)",
    budget: 9_400_000,
    headId: "apex-emp-011",
  },
  {
    id: "apex-hr",
    tenantId: "apex",
    name: "Human Resources",
    description: "Talent management, payroll and employee relations.",
    color: "var(--chart-1)",
    budget: 2_700_000,
    headId: "apex-emp-001",
  },
  {
    id: "apex-client-services",
    tenantId: "apex",
    name: "Client Services",
    description: "Relationship management and client support.",
    color: "var(--chart-2)",
    budget: 4_800_000,
    headId: "apex-emp-013",
  },

  // Horizon Logistics
  {
    id: "horizon-fleet",
    tenantId: "horizon",
    name: "Fleet Operations",
    description: "Vehicle fleet management, drivers and routing.",
    color: "var(--chart-1)",
    budget: 14_200_000,
    headId: "horizon-emp-002",
  },
  {
    id: "horizon-warehouse",
    tenantId: "horizon",
    name: "Warehouse & Distribution",
    description: "Warehousing, stock control and dispatch.",
    color: "var(--chart-2)",
    budget: 9_800_000,
    headId: "horizon-emp-004",
  },
  {
    id: "horizon-supply-chain",
    tenantId: "horizon",
    name: "Supply Chain Planning",
    description: "Demand planning, procurement and vendor management.",
    color: "var(--chart-3)",
    budget: 4_100_000,
    headId: "horizon-emp-006",
  },
  {
    id: "horizon-finance",
    tenantId: "horizon",
    name: "Finance",
    description: "Accounting, billing and payroll administration.",
    color: "var(--chart-4)",
    budget: 2_600_000,
    headId: "horizon-emp-008",
  },
  {
    id: "horizon-hr",
    tenantId: "horizon",
    name: "Human Resources",
    description: "Recruitment, compliance and workforce planning.",
    color: "var(--chart-5)",
    budget: 1_700_000,
    headId: "horizon-emp-001",
  },
  {
    id: "horizon-sales",
    tenantId: "horizon",
    name: "Sales & Accounts",
    description: "Client accounts, quoting and contract management.",
    color: "var(--chart-1)",
    budget: 3_300_000,
    headId: "horizon-emp-010",
  },
  {
    id: "horizon-it",
    tenantId: "horizon",
    name: "IT & Systems",
    description: "Tracking systems, infrastructure and support.",
    color: "var(--chart-2)",
    budget: 2_200_000,
    headId: "horizon-emp-012",
  },
];

export function getDepartmentsByTenant(tenantId: string): Department[] {
  return departments.filter((d) => d.tenantId === tenantId);
}
