import type { LeaveRequest } from "@/lib/types";

export const leaveRequests: LeaveRequest[] = [
  // NovaTech Solutions
  {
    id: "novatech-leave-001",
    tenantId: "novatech",
    employeeId: "novatech-emp-005",
    type: "annual",
    startDate: "2026-06-09",
    endDate: "2026-06-13",
    days: 5,
    reason: "Family vacation to Mauritius, booked since March.",
    status: "approved",
    appliedOn: "2026-05-12",
    decidedBy: "Lerato Dlamini",
    decidedOn: "2026-05-13",
  },
  {
    id: "novatech-leave-002",
    tenantId: "novatech",
    employeeId: "novatech-emp-003",
    type: "sick",
    startDate: "2026-06-10",
    endDate: "2026-06-11",
    days: 2,
    reason: "Flu, doctor's note attached.",
    status: "approved",
    appliedOn: "2026-06-10",
    decidedBy: "Thabo Nkosi",
    decidedOn: "2026-06-10",
  },
  {
    id: "novatech-leave-003",
    tenantId: "novatech",
    employeeId: "novatech-emp-009",
    type: "annual",
    startDate: "2026-06-22",
    endDate: "2026-06-26",
    days: 5,
    reason: "Family event in Durban, flights already booked.",
    status: "pending",
    appliedOn: "2026-06-08",
  },
  {
    id: "novatech-leave-004",
    tenantId: "novatech",
    employeeId: "novatech-emp-004",
    type: "family",
    startDate: "2026-06-15",
    endDate: "2026-06-15",
    days: 1,
    reason: "School orientation day for my daughter.",
    status: "pending",
    appliedOn: "2026-06-09",
  },
  {
    id: "novatech-leave-005",
    tenantId: "novatech",
    employeeId: "novatech-emp-012",
    type: "unpaid",
    startDate: "2026-07-01",
    endDate: "2026-07-03",
    days: 3,
    reason: "Extended family visiting from out of town.",
    status: "pending",
    appliedOn: "2026-06-07",
  },
  {
    id: "novatech-leave-006",
    tenantId: "novatech",
    employeeId: "novatech-emp-011",
    type: "annual",
    startDate: "2026-05-20",
    endDate: "2026-05-22",
    days: 3,
    reason: "Short break before month end.",
    status: "rejected",
    appliedOn: "2026-05-10",
    decidedBy: "Lerato Dlamini",
    decidedOn: "2026-05-11",
    decisionNote: "Please reschedule outside the month-end payroll processing window.",
  },
  {
    id: "novatech-leave-007",
    tenantId: "novatech",
    employeeId: "novatech-emp-008",
    type: "annual",
    startDate: "2026-07-10",
    endDate: "2026-07-17",
    days: 6,
    reason: "Annual family holiday to the Garden Route.",
    status: "approved",
    appliedOn: "2026-05-30",
    decidedBy: "Lerato Dlamini",
    decidedOn: "2026-06-01",
  },

  // Apex Financial Group
  {
    id: "apex-leave-001",
    tenantId: "apex",
    employeeId: "apex-emp-010",
    type: "sick",
    startDate: "2026-06-08",
    endDate: "2026-06-12",
    days: 5,
    reason: "Recovering from a minor medical procedure.",
    status: "approved",
    appliedOn: "2026-06-05",
    decidedBy: "Nokuthula Ndlovu",
    decidedOn: "2026-06-05",
  },
  {
    id: "apex-leave-002",
    tenantId: "apex",
    employeeId: "apex-emp-004",
    type: "annual",
    startDate: "2026-06-29",
    endDate: "2026-07-03",
    days: 5,
    reason: "Wedding anniversary trip, flights confirmed.",
    status: "pending",
    appliedOn: "2026-06-06",
  },
  {
    id: "apex-leave-003",
    tenantId: "apex",
    employeeId: "apex-emp-008",
    type: "family",
    startDate: "2026-06-18",
    endDate: "2026-06-18",
    days: 1,
    reason: "Attending my child's medical appointment.",
    status: "pending",
    appliedOn: "2026-06-09",
  },
  {
    id: "apex-leave-004",
    tenantId: "apex",
    employeeId: "apex-emp-012",
    type: "annual",
    startDate: "2026-06-05",
    endDate: "2026-06-06",
    days: 2,
    reason: "Personal time off, short notice.",
    status: "rejected",
    appliedOn: "2026-06-03",
    decidedBy: "James Wilson",
    decidedOn: "2026-06-03",
    decisionNote: "Quarter-end reporting requires full team availability. Please resubmit for next month.",
  },
  {
    id: "apex-leave-005",
    tenantId: "apex",
    employeeId: "apex-emp-006",
    type: "sick",
    startDate: "2026-06-02",
    endDate: "2026-06-03",
    days: 2,
    reason: "Migraine, unable to work.",
    status: "approved",
    appliedOn: "2026-06-02",
    decidedBy: "Anita Govender",
    decidedOn: "2026-06-02",
  },
  {
    id: "apex-leave-006",
    tenantId: "apex",
    employeeId: "apex-emp-003",
    type: "annual",
    startDate: "2026-08-03",
    endDate: "2026-08-14",
    days: 10,
    reason: "Overseas travel for a family commitment.",
    status: "pending",
    appliedOn: "2026-06-04",
  },

  // Horizon Logistics
  {
    id: "horizon-leave-001",
    tenantId: "horizon",
    employeeId: "horizon-emp-005",
    type: "annual",
    startDate: "2026-06-09",
    endDate: "2026-06-16",
    days: 6,
    reason: "Annual leave to spend time with family.",
    status: "approved",
    appliedOn: "2026-05-20",
    decidedBy: "Marike Steyn",
    decidedOn: "2026-05-21",
  },
  {
    id: "horizon-leave-002",
    tenantId: "horizon",
    employeeId: "horizon-emp-003",
    type: "sick",
    startDate: "2026-06-10",
    endDate: "2026-06-10",
    days: 1,
    reason: "Doctor's appointment, follow-up required.",
    status: "approved",
    appliedOn: "2026-06-09",
    decidedBy: "Pieter van der Merwe",
    decidedOn: "2026-06-09",
  },
  {
    id: "horizon-leave-003",
    tenantId: "horizon",
    employeeId: "horizon-emp-007",
    type: "annual",
    startDate: "2026-06-24",
    endDate: "2026-06-27",
    days: 4,
    reason: "Long weekend trip to Cape Town.",
    status: "pending",
    appliedOn: "2026-06-08",
  },
  {
    id: "horizon-leave-004",
    tenantId: "horizon",
    employeeId: "horizon-emp-009",
    type: "family",
    startDate: "2026-06-20",
    endDate: "2026-06-20",
    days: 1,
    reason: "Attending my sibling's graduation ceremony.",
    status: "pending",
    appliedOn: "2026-06-10",
  },
  {
    id: "horizon-leave-005",
    tenantId: "horizon",
    employeeId: "horizon-emp-010",
    type: "unpaid",
    startDate: "2026-07-15",
    endDate: "2026-07-17",
    days: 3,
    reason: "Personal travel to attend to a property matter.",
    status: "pending",
    appliedOn: "2026-06-09",
  },
  {
    id: "horizon-leave-006",
    tenantId: "horizon",
    employeeId: "horizon-emp-012",
    type: "annual",
    startDate: "2026-05-01",
    endDate: "2026-05-05",
    days: 5,
    reason: "Planned leave around the public holiday.",
    status: "rejected",
    appliedOn: "2026-04-15",
    decidedBy: "Sipho Mokoena",
    decidedOn: "2026-04-16",
    decisionNote: "Annual leave balance was insufficient for the full week. Please apply for fewer days.",
  },
];

export function getLeaveRequestsByTenant(tenantId: string): LeaveRequest[] {
  return leaveRequests
    .filter((r) => r.tenantId === tenantId)
    .sort((a, b) => b.appliedOn.localeCompare(a.appliedOn));
}

export function getLeaveRequestsByEmployee(employeeId: string): LeaveRequest[] {
  return leaveRequests
    .filter((r) => r.employeeId === employeeId)
    .sort((a, b) => b.appliedOn.localeCompare(a.appliedOn));
}
