import type { Metadata } from "next";
import { LegalPage } from "@/components/marketing/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy | NovaHR",
  description: "How NovaHR collects, uses and protects personal information.",
};

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      effectiveDate="1 July 2026"
      intro="This Privacy Policy explains how NovaHR collects, uses, stores and protects personal information when you use our platform. We process personal information in accordance with the Protection of Personal Information Act, 2013 (POPIA). For employee data loaded into a customer workspace, the customer is the responsible party and NovaHR acts as operator processing that data on the customer's instructions."
      sections={[
        {
          heading: "Information we collect",
          paragraphs: [
            "We collect information you provide directly and information generated by using the Service:",
          ],
          bullets: [
            "Account information: your name, email address, company name and password (stored as a secure hash by our authentication provider).",
            "Employee records loaded by your workspace administrators: names, contact details, identity numbers, tax numbers, banking details, compensation, leave and payroll history, and supporting documents such as medical certificates.",
            "Technical information: log data, device and browser information, and cookies required to keep you signed in.",
          ],
        },
        {
          heading: "How we use information",
          paragraphs: ["We use personal information only to:"],
          bullets: [
            "Provide, operate and secure the Service, including payroll calculation and payslip generation.",
            "Send service emails such as leave notifications, payslip alerts and account invitations.",
            "Respond to support requests and communicate about your subscription.",
            "Comply with legal obligations.",
          ],
        },
        {
          heading: "What we do not do",
          paragraphs: [],
          bullets: [
            "We do not sell personal information.",
            "We do not use employee data for advertising.",
            "We do not share workspace data with other customers; every workspace is isolated at the database level.",
          ],
        },
        {
          heading: "Storage and security",
          paragraphs: [
            "Data is hosted with reputable cloud providers (Supabase for the database and authentication, Vercel for the application). Safeguards include encryption in transit, row-level security enforcing tenant isolation, role-based access controls in the application, and hashed one-time tokens for account invitations.",
            "Despite these measures no system is completely secure. If we become aware of a data breach affecting your personal information we will notify you and the Information Regulator as required by POPIA section 22.",
          ],
        },
        {
          heading: "Retention",
          paragraphs: [
            "We keep personal information for as long as the customer workspace is active. Payroll records may need to be retained by employers for statutory periods (for example, five years for tax records); customers can export their data at any time. After account closure we delete or de-identify data within a reasonable period unless retention is required by law.",
          ],
        },
        {
          heading: "Your rights",
          paragraphs: [
            "Under POPIA, data subjects may request access to, correction of, or deletion of their personal information. Employees whose data is managed by their employer in NovaHR should direct requests to their employer as the responsible party; we will assist the employer in fulfilling them. You can contact us directly at mtshwenewesley@gmail.com.",
            "You also have the right to lodge a complaint with the Information Regulator (South Africa) at inforeg.org.za.",
          ],
        },
        {
          heading: "Cookies",
          paragraphs: [
            "We use only strictly necessary cookies: session cookies from our authentication provider that keep you signed in, and a preference cookie for your light or dark theme. We do not use third-party advertising or analytics cookies.",
          ],
        },
        {
          heading: "Changes to this policy",
          paragraphs: [
            "We may update this policy from time to time. Material changes will be announced in the app or by email before they take effect. The effective date above reflects the latest revision.",
          ],
        },
      ]}
    />
  );
}
