import { Prisma } from "@prisma/client";
import type { Tenant as PrismaTenant } from "@prisma/client";
import type { Employee } from "../types";
import type { EmployeeWithBalances } from "./mappers";

export function makeEmployeeRow(overrides: Partial<EmployeeWithBalances> = {}): EmployeeWithBalances {
  return {
    id: "emp-1",
    tenantId: "novatech",
    employeeNumber: "NT-0001",
    firstName: "Aisha",
    lastName: "Patel",
    preferredName: null,
    email: "aisha.patel@example.com",
    phone: "+27 71 000 0000",
    avatarColor: "#4C6FFF",
    initials: "AP",
    photoUrl: null,
    jobTitle: "Software Engineer",
    department: "Engineering",
    employmentType: "full_time",
    status: "active",
    startDate: new Date("2024-01-15T00:00:00Z"),
    location: "Cape Town",
    managerId: null,
    salaryAnnualGross: new Prisma.Decimal(600_000),
    salaryCurrency: "ZAR",
    salaryPayFrequency: "monthly",
    salaryTravelAllowance: null,
    salaryHousingAllowance: null,
    salaryPensionContributionPct: null,
    salaryMedicalAid: null,
    salaryRetirementAnnuity: null,
    salaryEmployerBenefits: null,
    bankName: "Standard Bank",
    bankAccountNumber: "1234567890",
    bankBranchCode: "051001",
    bankAccountType: "Cheque",
    bankAccountValidated: false,
    bankValidatedAt: null,
    taxNumber: "1234567890",
    idNumber: "9001015800082",
    address: "1 Main Street, Cape Town",
    emergencyContactName: "John Patel",
    emergencyContactRelationship: "Spouse",
    emergencyContactPhone: "+27 71 111 1111",
    equityRace: null,
    equityGender: null,
    occupationalLevel: null,
    foreignNational: false,
    hasDisability: false,
    onboarding: null,
    createdAt: new Date("2024-01-15T00:00:00Z"),
    updatedAt: new Date("2024-01-15T00:00:00Z"),
    leaveBalances: [
      { id: "lb-1", employeeId: "emp-1", type: "annual", total: 18, used: 0 },
      { id: "lb-2", employeeId: "emp-1", type: "sick", total: 10, used: 0 },
      { id: "lb-3", employeeId: "emp-1", type: "unpaid", total: 5, used: 0 },
      { id: "lb-4", employeeId: "emp-1", type: "family", total: 3, used: 0 },
    ],
    ...overrides,
  };
}

export function makeTenantRow(overrides: Partial<PrismaTenant> = {}): PrismaTenant {
  return {
    id: "novatech",
    name: "NovaTech Solutions",
    legalName: "NovaTech Solutions (Pty) Ltd",
    initials: "NT",
    industry: "Software & Technology",
    color: "#4C6FFF",
    founded: "2018",
    currency: "ZAR",
    payFrequency: "monthly",
    registrationNumber: "2018/123456/07",
    vatNumber: "4480123456",
    address: "12 Bree Street, Cape Town, 8001",
    city: "Cape Town",
    payDay: 25,
    bankName: "First National Bank",
    primaryContact: "Lerato Dlamini",
    plan: "scale",
    trialEndsAt: null,
    stripeCustomerId: null,
    stripeSubscriptionId: null,
    subscriptionStatus: null,
    currentPeriodEnd: null,
    payrollDisclaimerAcceptedAt: null,
    createdAt: new Date("2026-01-01T00:00:00Z"),
    updatedAt: new Date("2026-01-01T00:00:00Z"),
    ...overrides,
  };
}

export function makeEmployee(overrides: Partial<Employee> = {}): Employee {
  return {
    id: "emp-1",
    tenantId: "novatech",
    employeeNumber: "NT-0001",
    firstName: "Aisha",
    lastName: "Patel",
    email: "aisha.patel@example.com",
    phone: "+27 71 000 0000",
    avatarColor: "#4C6FFF",
    initials: "AP",
    jobTitle: "Software Engineer",
    department: "Engineering",
    employmentType: "full_time",
    status: "active",
    startDate: "2024-01-15",
    location: "Cape Town",
    salary: { annualGross: 600_000, currency: "ZAR", payFrequency: "monthly" },
    bankDetails: {
      bank: "Standard Bank",
      accountNumber: "1234567890",
      branchCode: "051001",
      accountType: "Cheque",
      validated: false,
      validatedAt: null,
    },
    taxNumber: "1234567890",
    idNumber: "9001015800082",
    address: "1 Main Street, Cape Town",
    emergencyContact: { name: "John Patel", relationship: "Spouse", phone: "+27 71 111 1111" },
    leaveBalances: [
      { type: "annual", total: 18, used: 0 },
      { type: "sick", total: 10, used: 0 },
      { type: "unpaid", total: 5, used: 0 },
      { type: "family", total: 3, used: 0 },
    ],
    ...overrides,
  };
}
